### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by thesofakillers** [linclab/ltlwdp#1]
Hi, any plans to release the code? I see this repository linked in the published paper for implementation details.

**Comment by tyrellTuring** [comment]
Ooops, that's an error. Sorry about that. We'll get the code up ASAP.

Blake

**Comment by thesofakillers** [comment]
Hi there, any updates on the code? Thanks!

**Comment by jcornford** [comment]
I'm sorry for the delay on this. I've just added it now.
